
const config = {
    persons : {
        URL_person_01: process.env.PUBLIC_URL + "/assets/img/person_01.jpg",
        URL_person_02: process.env.PUBLIC_URL + "/assets/img/person_02.jpg",
        URL_person_03: process.env.PUBLIC_URL + "/assets/img/person_03.jpg",
        URL_person_04: process.env.PUBLIC_URL + "/assets/img/person_04.jpg",
        URL_person_05: process.env.PUBLIC_URL + "/assets/img/person_05.jpg",
        URL_person_06: process.env.PUBLIC_URL + "/assets/img/person_06.jpg",
        URL_person_07: process.env.PUBLIC_URL + "/assets/img/person_07.jpg",
        URL_person_08: process.env.PUBLIC_URL + "/assets/img/person_08.jpg",
        URL_person_09: process.env.PUBLIC_URL + "/assets/img/person_09.jpg",
        URL_person_10: process.env.PUBLIC_URL + "/assets/img/person_10.jpg",
    },
    background : {
        URL_background_01: process.env.PUBLIC_URL + "/assets/img/background_01.jpg",
        URL_background_02: process.env.PUBLIC_URL + "/assets/img/background_02.jpg",
    },
    rank : {
        URL_rank_01: process.env.PUBLIC_URL + "/assets/img/rank_01.jpg",
        URL_rank_02: process.env.PUBLIC_URL + "/assets/img/rank_02.jpg",
        URL_rank_03: process.env.PUBLIC_URL + "/assets/img/rank_03.jpg",
        URL_rank_04: process.env.PUBLIC_URL + "/assets/img/rank_04.jpg",
    },
    default : {
        URL_default: process.env.PUBLIC_URL + "/assets/img/default.jpg",
        URL_placeholder: process.env.PUBLIC_URL + "/assets/img/placeholder.jpg"
    },
    crown : {
        URL_crown_01: process.env.PUBLIC_URL + "/assets/img/crown_01.png",
        URL_crown_02: process.env.PUBLIC_URL + "/assets/img/crown_02.png",
        URL_crown_03: process.env.PUBLIC_URL + "/assets/img/crown_03.png",
    },
    audio : {
        URL_button_01: process.env.PUBLIC_URL + "/assets/audio/BUTTON.mp3",
        URL_overlay_01: process.env.PUBLIC_URL + "/assets/audio/OBELISK.mp3",
        URL_overlay_02: process.env.PUBLIC_URL + "/assets/audio/PLAYCOME.mp3",
    },
    level_up : {
        URL_level_up_01: process.env.PUBLIC_URL + "/assets/img/level_up_01.png",
        URL_level_up_02: process.env.PUBLIC_URL + "/assets/img/level_up_02.png",
        URL_level_up_03: process.env.PUBLIC_URL + "/assets/img/level_up_03.png",
        URL_level_up_04: process.env.PUBLIC_URL + "/assets/img/level_up_04.png",
        URL_level_up_05: process.env.PUBLIC_URL + "/assets/img/level_up_05.png",
        URL_level_up_06: process.env.PUBLIC_URL + "/assets/img/level_up_06.png",
        URL_level_up_07: process.env.PUBLIC_URL + "/assets/img/level_up_07.png",
        URL_level_up_08: process.env.PUBLIC_URL + "/assets/img/level_up_08.png",
        URL_level_up_09: process.env.PUBLIC_URL + "/assets/img/level_up_09.png",
        URL_level_up_10: process.env.PUBLIC_URL + "/assets/img/level_up_10.png",
        URL_level_up_11: process.env.PUBLIC_URL + "/assets/img/level_up_11.png",
        URL_level_up_12: process.env.PUBLIC_URL + "/assets/img/level_up_12.png",
        URL_level_up_13: process.env.PUBLIC_URL + "/assets/img/level_up_13.png",
        URL_level_up_14: process.env.PUBLIC_URL + "/assets/img/level_up_14.png",
        URL_level_up_15: process.env.PUBLIC_URL + "/assets/img/level_up_15.png",
        URL_level_up_16: process.env.PUBLIC_URL + "/assets/img/level_up_16.png",
        URL_level_up_17: process.env.PUBLIC_URL + "/assets/img/level_up_17.png",
        URL_level_up_18: process.env.PUBLIC_URL + "/assets/img/level_up_18.png",
        URL_level_up_19: process.env.PUBLIC_URL + "/assets/img/level_up_19.png",
        URL_level_up_20: process.env.PUBLIC_URL + "/assets/img/level_up_20.png",
        URL_level_up_21: process.env.PUBLIC_URL + "/assets/img/level_up_21.png",
    },
    level_equal : {
        URL_level_equal_01: process.env.PUBLIC_URL + "/assets/img/level_equal_01.png",
        URL_level_equal_02: process.env.PUBLIC_URL + "/assets/img/level_equal_02.png",
        URL_level_equal_03: process.env.PUBLIC_URL + "/assets/img/level_equal_03.png",
        URL_level_equal_04: process.env.PUBLIC_URL + "/assets/img/level_equal_04.png",
        URL_level_equal_05: process.env.PUBLIC_URL + "/assets/img/level_equal_05.png",
        URL_level_equal_06: process.env.PUBLIC_URL + "/assets/img/level_equal_06.png",
        URL_level_equal_07: process.env.PUBLIC_URL + "/assets/img/level_equal_07.png",
        URL_level_equal_08: process.env.PUBLIC_URL + "/assets/img/level_equal_08.png",
        URL_level_equal_09: process.env.PUBLIC_URL + "/assets/img/level_equal_09.png",
        URL_level_equal_10: process.env.PUBLIC_URL + "/assets/img/level_equal_10.png",
        URL_level_equal_11: process.env.PUBLIC_URL + "/assets/img/level_equal_11.png",
        URL_level_equal_12: process.env.PUBLIC_URL + "/assets/img/level_equal_12.png",
        URL_level_equal_13: process.env.PUBLIC_URL + "/assets/img/level_equal_13.png",
        URL_level_equal_14: process.env.PUBLIC_URL + "/assets/img/level_equal_14.png",
        URL_level_equal_15: process.env.PUBLIC_URL + "/assets/img/level_equal_15.png",
        URL_level_equal_16: process.env.PUBLIC_URL + "/assets/img/level_equal_16.png",
        URL_level_equal_17: process.env.PUBLIC_URL + "/assets/img/level_equal_17.png",
        URL_level_equal_18: process.env.PUBLIC_URL + "/assets/img/level_equal_18.png",
        URL_level_equal_19: process.env.PUBLIC_URL + "/assets/img/level_equal_19.png",
        URL_level_equal_20: process.env.PUBLIC_URL + "/assets/img/level_equal_20.png",
    },
    level_down : {
        URL_level_down_01: process.env.PUBLIC_URL + "/assets/img/level_down_01.png",
        URL_level_down_02: process.env.PUBLIC_URL + "/assets/img/level_down_02.png",
        URL_level_down_03: process.env.PUBLIC_URL + "/assets/img/level_down_03.png",
        URL_level_down_04: process.env.PUBLIC_URL + "/assets/img/level_down_04.png",
        URL_level_down_05: process.env.PUBLIC_URL + "/assets/img/level_down_05.png",
        URL_level_down_06: process.env.PUBLIC_URL + "/assets/img/level_down_06.png",
        URL_level_down_07: process.env.PUBLIC_URL + "/assets/img/level_down_07.png",
        URL_level_down_08: process.env.PUBLIC_URL + "/assets/img/level_down_08.png",
        URL_level_down_09: process.env.PUBLIC_URL + "/assets/img/level_down_09.png",
        URL_level_down_10: process.env.PUBLIC_URL + "/assets/img/level_down_10.png",
        URL_level_down_11: process.env.PUBLIC_URL + "/assets/img/level_down_11.png",
        URL_level_down_12: process.env.PUBLIC_URL + "/assets/img/level_down_12.png",
        URL_level_down_13: process.env.PUBLIC_URL + "/assets/img/level_down_13.png",
        URL_level_down_14: process.env.PUBLIC_URL + "/assets/img/level_down_14.png",
        URL_level_down_15: process.env.PUBLIC_URL + "/assets/img/level_down_15.png",
        URL_level_down_16: process.env.PUBLIC_URL + "/assets/img/level_down_16.png",
        URL_level_down_17: process.env.PUBLIC_URL + "/assets/img/level_down_17.png",
        URL_level_down_18: process.env.PUBLIC_URL + "/assets/img/level_down_18.png",
        URL_level_down_19: process.env.PUBLIC_URL + "/assets/img/level_down_19.png",
        URL_level_down_20: process.env.PUBLIC_URL + "/assets/img/level_down_20.png",
    }
}

export default config